name: RestartUtil
main: at.jojokobi.restartutil.RestartUtilPlugin
author: jojokobi
version: 0.1
api-version: 1.20
commands:
  interruptrestart:
    description: Interrupts the restart timer
    usage: /interruptrestart